config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get :dashboard, to: "dashboard#index"
  get :profile, to: "profile#show"
  put :profile, to: "profile#update"

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: :create
  end
  resources :bookmarks, only: :index
  resources :usernames, only: [:new, :update]
  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end
  resources :hashtags, only: [:show, :index], path: "/explore"
  resources :message_threads, only: :index, path: "messages"
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  HASHTAG_REGEX = /(#\w+)/

  belongs_to :user

  validates :body, presence: true, length: { maximum: 280 }
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :retweets, dependent: :destroy
  has_many :retweeted_users, through: :retweets, source: :user
  has_many :views, dependent: :destroy
  has_many :viewd_users, through: :views, source: :user
  has_and_belongs_to_many :hashtags
  belongs_to :parent_tweet, inverse_of: :reply_tweets, foreign_key: :parent_tweet_id, class_name: "Tweet",
                            optional: true, counter_cache: :reply_tweets_count
  has_many :reply_tweets, foreign_key: :parent_tweet_id, class_name: "Tweet"

  before_save :parse_and_save_hashtag
  def parse_and_save_hashtag
    matches = body.scan(HASHTAG_REGEX)
    return if matches.empty?

    matches.flatten.each do |tag|
      hashtag = Hashtag.find_or_create_by(tag: tag.remove("#"))
      hashtags << Hashtag.find_or_create_by(tag: tag.remove("#"))
    end
  end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :authenticate_user!

  def show
    ViewTweetJob.perform_async(tweet.id, current_user.id)
    @tweet_presenter = TweetPresenter.new(tweet:, current_user:)
    @reply_tweets_in_presenter = tweet.reply_tweets.includes(:liked_users, :bookmarked_users, :retweeted_users,
                                                             :user).order(created_at: :desc).map do |reply_tweet|
      TweetPresenter.new(tweet: reply_tweet, current_user:)
    end
  end

  def create
    @tweet = Tweet.new(tweets_params.merge(user: current_user))

    return unless @tweet.save

    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  private

  def tweets_params
    params.require(:tweet).permit(:body)
  end

  def tweet
    @tweet ||= Tweet.find(params[:id])
  end
end

app/views/tweets/_show_stats.html.erb
<div id="tweet_stats">
  <div class="d-flex justify-content-start mb-4">
    <div class="me-4"><span class="fw-bold"><%= tweet_presenter.views_count %></span> Views</div>
    <div class="me-4"><span class="fw-bold"><%= tweet_presenter.reply_tweets_count %></span> Replies</div>
    <div class="me-4"><span class="fw-bold"><%= tweet_presenter.retweets_count %></span> Retweets</div>
    <div class="me-4"><span class="fw-bold"><%= tweet_presenter.likes_count %></span> Likes</div>
  </div>

  <div class="d-flex justify-content-evenly align-items-center action-links">
    <div>
      <%= link_to tweet_path(tweet_presenter.tweet), class: "text-decoration-none text-black replies" do %>
        <%= image_tag "speech-bubble.png", size: "23x23", class: "me-2" %>
      <% end %>
    </div>
    <div>
      <%= link_to tweet_presenter.retweet_tweet_url(source: "tweet_show"), data: { "turbo-method": tweet_presenter.turbo_retweet_data_method }, class: "text-decoration-none text-black retweet" do %>
        <%= image_tag tweet_presenter.retweet_image, size: "23x23", class: "me-2" %>
      <% end %>
    </div>
    <div>
      <%= link_to tweet_presenter.like_tweet_url(source: "tweet_show"), data: { "turbo-method": tweet_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do %>
        <%= image_tag tweet_presenter.like_heart_image, size: "23x23", class: "me-2" %>
      <% end %>
    </div>
    <div>
      <%= link_to "#", class: "text-decoration-none text-black views" do %>
        <%= image_tag "bar-chart.png", size: "23x23", class: "me-2" %>
      <% end %>
    </div>
    <div>
      <%= link_to tweet_presenter.bookmark_tweet_url(source: "tweet_show"), data: { "turbo-method": tweet_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black bookmark " do %>
        <%= image_tag tweet_presenter.bookmark_image, size: "23x23", class: "me-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag dom_id(tweet_presenter.tweet) do%>
  <div data-controller="tweet-card" data-tweet-path="<%= tweet_path(tweet_presenter.tweet) %>" class="tweet d-flex py-3 px-3 hover">
    <div class="flex-shrink-0">
      <%= image_tag tweet_presenter.avatar, size: "48x48", class: "rounded-circle" %>
    </div>
    <div class="flex-grow-1 ms-3">
      <p class="mb-0">
        <span class="fw-bolder"><%= tweet_presenter.display_name  %></span>
        <span class="text-secondary">
        @<%= tweet_presenter.username  %> · <%= tweet_presenter.created_at %></span>
      </p>
      <%= tweet_presenter.body_html.html_safe  %>

      <div class="d-flex justify-content-between align-items-center action-links">
        <div>
          <%= link_to tweet_path(tweet_presenter.tweet), data: { "ignore-click": true }, class: "text-decoration-none text-black replies" do %>
            <%= image_tag "speech-bubble.png", size: "19x19", class: "me-2" %>
            <span><%= tweet_presenter.reply_tweets_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to tweet_presenter.retweet_tweet_url, data: { "ignore-click": true, "turbo-method": tweet_presenter.turbo_retweet_data_method }, class: "text-decoration-none text-black retweet" do %>
            <%= image_tag tweet_presenter.retweet_image, size: "19x19", class: "me-2" %>
            <span><%= tweet_presenter.retweets_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to tweet_presenter.like_tweet_url, data: { "ignore-click": true, "turbo-method": tweet_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do %>
            <%= image_tag tweet_presenter.like_heart_image, size: "19x19", class: "me-2" %>
            <span><%= tweet_presenter.likes_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to tweet_path(tweet_presenter.tweet), data: { "ignore-click": true }, class: "text-decoration-none text-black views" do %>
            <%= image_tag "bar-chart.png", size: "19x19", class: "me-2" %>
            <span><%= tweet_presenter.views_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to tweet_presenter.bookmark_tweet_url, data: { "ignore-click": true, "turbo-method": tweet_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black bookmark " do %>
            <%= image_tag tweet_presenter.bookmark_image, size: "19x19", class: "me-2" %>
            <span><%= tweet_presenter.bookmark_text %></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/create.turbo_stream.erb
<%= turbo_stream.prepend "tweets" do %>
  <%= render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(tweet: @tweet, current_user: current_user) } %>
<%end%>

app/views/tweets/show.html.erb
<div class="col-7">
  <div class="mb-3">
    <%= link_to :back, class: "fs-4 text-decoration-none text-black fw-semibold" do %>
      <%= image_tag "back-arrow.png", size: "28x28", class: "me-4" %>
      <span style="position: relative; top: 2px;">Tweet</span>
    <% end %>

    <div class="tweet d-flex py-3 px-3">
      <div class="flex-shrink-0">
        <%= image_tag @tweet_presenter.avatar, size: "48x48", class: "rounded-circle" %>
      </div>
      <div class="flex-grow-1 ms-3">
        <p class="fw-bolder mb-0"><%= @tweet_presenter.display_name  %></p>
        <p class="text-secondary mb-1">@<%= @tweet_presenter.username  %></p>
        <%= @tweet_presenter.body_html(p_class: "fs-2 mb-1").html_safe %>
        <p class="text-secondary"><%= @tweet_presenter.tweet.created_at.strftime("%l:%M %p · %b %d, %Y") %></p>

        <%= render "show_stats", tweet_presenter: @tweet_presenter %>
      </div>
    </div>
  </div>
  <%= render "shared/tweet_form", form_submit_path: tweet_reply_tweets_path(@tweet_presenter.tweet), button_label: "Reply", tweet_placeholder: "Tweet your reply" %>

  <div id="reply_tweets">
    <%= render partial: "tweets/tweet", collection: @reply_tweets_in_presenter, as: :tweet_presenter %>
  </div>
</div>
<div class="col">
  Column
</div>