config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get :dashboard, to: "dashboard#index"
  get :profile, to: "profile#show"
  put :profile, to: "profile#update"

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: :create
  end
  resources :bookmarks, only: :index
  resources :usernames, only: [:new, :update]
  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end
  resources :hashtags, only: [:show, :index], path: "/explore"
  resources :message_threads, only: :index, path: "messages"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets,  through: :likes, source: :tweet
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_tweets, through: :bookmarks, source: :tweet
  has_many :retweets, dependent: :destroy
  has_many :retweeted_tweets, through: :retweets, source: :tweet
  has_many :views
  has_many :viewd_tweets, through: :views, source: :tweet
  has_many :followings, dependent: :destroy
  has_many :following_users, through: :followings, source: :following_user
  has_many :reverse_followings, foreign_key: :following_user_id, class_name: "Following"
  has_many :followers, through: :reverse_followings, source: :user
  has_many :messages
  has_and_belongs_to_many :message_threads

  validates :username, uniqueness: { case_sensitive: false }, allow_blank: true

  before_save :set_display_name, if: -> { username.present? && display_name.blank? }

  def set_display_name
    self.display_name = username.humanize
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    redirect_to profile_path if params[:id].to_i == current_user.id
    @user = User.find(params[:id])
    @tweet_presenters = @user.tweets.map do |tweet|
      TweetPresenter.new(tweet:, current_user: @user)
    end
  end
end

app/views/users/_follow_button.html.erb
<%= turbo_frame_tag "follow-unfollow-button" do %>
  <% if user.followers.include?(current_user) %>
    <%= link_to "Unfollow", user_following_path(user, current_user.followings.find_by(following_user_id: user)), data: { "turbo-method": :delete }, class: "btn btn-twitter-outline rounded-pill" %>
  <% else %>
    <%= link_to "Follow", user_followings_path(current_user, following_user_id: user.id), data: { "turbo-method": :post }, class: "btn btn-twitter-outline rounded-pill" %>
  <% end %>
<% end %>

app/views/users/_profile_section.html.erb
<%= turbo_frame_tag "profile-section" do %>
  <div class="mb-5">
    <%= link_to :back, class: "fs-4 text-decoration-none text-black fw-semibold" do %>
      <%= image_tag "back-arrow.png", size: "28x28", class: "me-4" %>
      <span style="position: relative; top: 2px;"><%= @user.username %></span>
      <span class="text-secondary fs-6" style="position: relative; top: 2px;"><%= @user.tweets.size %> Tweets</span>
    <% end %>
  </div>

  <div class="d-flex justify-content-between align-items-center mb-5">
    <div>
      <% if @user.avatar.present?%>
        <%= image_tag @user.avatar, class: "rounded-circle", size: "150x150" %>
      <% else %>
        <%= image_tag "user.png", class: "rounded-circle", size: "150x150" %>
      <% end %>
    </div>
    <% if controller_name == "profile" %>
      <div><%= button_tag "Edit Profile", data: {"bs-toggle": "modal",  "bs-target": "#profile-edit-modal"}, class: "btn btn-twitter-outline rounded-pill" %></div>
    <% else %>
      <div>
        <%= link_to message_threads_path(user_id: @user.id), class: "btn btn-twitter-outline rounded-pill" do %>
          <%= image_tag "envelope.png", size: "25x25" %>
          Message
        <% end %>
        <%= render "users/follow_button", user: @user, current_user: current_user %>
      </div>
    <% end %>
  </div>
  
  <div>
    <p class="fs-3 fw-semibold mb-0"><%= user.display_name %></p>
    <p class="text-secondary">@<%= user.username %></p>
    <p><%= user.bio %></p>
    <div class="d-flex justify-content-start mb-3">
      <div class="me-4">
        <%= image_tag "location.png", size: "23x23", class: "me-1" %>
        <span class="text-secondary"><%= user.location %></span>
      </div>
      <div class="me-4">
        <%= image_tag "link.png", size: "23x23", class: "me-1" %>
        <span class="text-secondary"><%= link_to user.profile_url, user.profile_url ,target: :_blank %></span>
      </div>
      <div class="me-4">
        <%= image_tag "calendar.png", size: "23x23", class: "me-1" %>
        <span class="text-secondary">Joined <%= user.created_at.strftime("%B %Y") %></span>
      </div>
    </div>
    <div class="d-flex justify-content-start">
      <div class="me-4"><span class="fw-semibold"><%= user.following_count %></span>Following</div>
      <div><span class="fw-semibold"><%= user.follower_count %></span>Followers</div>
    </div>
  </div>
<% end %>

app/views/users/_tweets_collection.html.erb
<div class="mt-3" id="tweets-collection">
  <%= render partial: "tweets/tweet", collection: tweet_presenters, as: :tweet_presenter %>
</div>

app/views/users/show.html.erb
<div class="col-6">
  <div class="mb-3">
    <%= render "users/profile_section", user: @user %>
    <%= render "users/tweets_collection", tweet_presenters: @tweet_presenters %>
  </div>
</div>
<div class="col">
  <%= render "shared/hashtag_sidebar" %>
</div>

<% if controller_name == "profile" %>
  <!-- Profile Update Form Modal -->
  <div class="modal" id="profile-edit-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header border-bottom-0">
          <button type="button" class="btn-close mx-0 close-modal-btn" data-bs-dismiss="modal" aria-label="Close" id="close-modal-button"></button>
        </div>
        <div class="modal-body">
          <%=  form_with model: @user, url: profile_path, data: { controller: "tweet-form" }, method: :put, class: "row g-3" do |f| %>
            <div class="col-md-12">
              <%= f.label :username, class: "form-label" %>
              <%= f.text_field  :username, class: "form-control" %>
            </div>
            <div class="col-md-12">
              <%= f.label :display_name, class: "form-label" %>
              <%= f.text_field :display_name, class: "form-control" %>
            </div>

            <div class="col-md-12">
              <%= f.label :email, class: "form-label" %>
              <%= f.password_field :email_field, class: "form-control" %>
            </div>

            <div class="col-md-12">
              <%= f.label :password, class: "form-label" %>
              <%= f.password_field :password, class: "form-control" %>
            </div>

            <div class="col-md-12">
              <%= f.label :bio, class: "form-label" %>
              <%= f.text_area :bio, class: "form-control" %>
            </div>

            <div class="input-group col-md-12">
              <%= f.label :avatar, class: "input-group-text" %>
              <%= f.file_field :avatar, class: "form-control" %>
            </div>

            <div class="col-md-12">
              <%= f.label :location, class: "form-label" %>
              <%= f.text_field :location, class: "form-control" %>
            </div>

            <div class="col-md-12">
              <%= f.label :url, class: "form-label" %>
              <%= f.text_field :url, class: "form-control" %>
            </div>

            <div class="col-12">
              <%= f.submit "Update Profile", class: "btn btn-twitter rounded-pill" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>