config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get :dashboard, to: "dashboard#index"
  get :profile, to: "profile#show"
  put :profile, to: "profile#update"

  resources :tweets, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
    resources :reply_tweets, only: :create
  end
  resources :bookmarks, only: :index
  resources :usernames, only: [:new, :update]
  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end
  resources :hashtags, only: [:show, :index], path: "/explore"
  resources :message_threads, only: :index, path: "messages"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_hashtag_sidebar.html.erb
<div class="hashtag-sidebar rounded p-3 mt-4">
  <p class="p-2 fs-5 mb-0 fw-bold"> What's happening </p>
  <% Hashtag.limit(5).each do |hashtag| %>
    <div class="item p-2" data-controller="hashtag" data-url="<%= hashtag_path(hashtag) %>">
      <p class="fw-bold mb-0 fs-5">#<%= hashtag.tag %></p>
      <p class="text-secondary fs-6 mb-0"><%= hashtag.tweets.size %> Tweets</p>
    </div>
  <% end %>

  <%= link_to "Show more", hashtags_path, class: "twitter-link p-2 text-decoration-none" %>
</div>

app/views/shared/_sidebar.html.erb
<aside class="col side-navbar">
  <%= link_to dashboard_path, class: "d-flex align-items-center fs-5 px-3 mb-3", id: "twitter-logo-link" do %>
    <div class="px-2 py-2 rounded-circle">
      <%= image_tag "twitter.png", width: 32 %> 
    </div>
  <% end %>

  <%= link_to dashboard_path, class: "d-flex align-items-center fs-5 mb-3 #{'fw-bold' if controller_name == 'dashboard'}" do %>
    <div class="px-3 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"> <%= image_tag "home.png", width: 32 %> </span> 
      Home
    </div>
  <% end %>

  <%= link_to hashtags_path, class: "d-flex align-items-center fs-5 mb-3 #{'fw-bold' if controller_name == 'hashtags'}" do %>
    <div class="px-3 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"> <%= image_tag "hashtag.png", width: 32 %> </span> 
      Explore
    </div>
  <% end %>

  <%= link_to "#", class: "d-flex align-items-center fs-5 mb-3" do %>
    <div class="px-3 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"> <%= image_tag "notifications.png", width: 32 %> </span> 
      Notifications
    </div>
  <% end %>

  <%= link_to message_threads_path, class: "d-flex align-items-center fs-5 mb-3 #{'fw-bold' if controller_name == 'message_threads'} " do %>
    <div class="px-3 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"> <%= image_tag "messages.png", width: 32 %> </span> 
      Messages
    </div>
  <% end %>

  <%= link_to bookmarks_path, class: "d-flex align-items-center fs-5 mb-3 #{'fw-bold' if controller_name == 'bookmarks'}" do %>
    <div class="px-3 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"> <%= image_tag "bookmark-unfilled.png", width: 32 %> </span> 
      Bookmarks
    </div>
  <% end %>

  <%= link_to profile_path, class: "d-flex align-items-center fs-5 mb-4 #{'fw-bold' if controller_name == 'profile'}" do %>
    <div class="px-3 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"> <%= image_tag "profile.png", width: 32 %> </span> 
      Profile
    </div>
  <% end %>

  <div class="d-flex align-items-center fs-4 mb-3 px-4">
    <%= button_tag "Tweet", class: "btn btn-lg btn-twitter w-100 rounded-pill", data: {"bs-toggle": "modal",  "bs-target": "#tweet-modal"} %>
  </div>

  <div class="d-flex align-items-center fs-6 px-4 ">
    <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "twitter-link" %>
  </div>
      
</aside>

<div class="modal" id="tweet-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        <button type="button" class="btn-close mx-0 close-modal-btn" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "shared/tweet_form", form_submit_path: tweets_path, button_label: "Tweet", tweet_placeholder: "What's happening?" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tweet_form.html.erb
<div class="tweet hover d-flex py-3 px-3">
  <div class="flex-shrink-0">
    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, size: "48x48", class: "rounded-circle" %>
    <% else %>
      <%= image_tag "user.png", size: "48x48", class: "rounded-circle" %>
    <% end %>
  </div>
  <div class="flex-grow-1 ms-3">
    <%= form_with model: Tweet.new, url: form_submit_path, method: :post, class: "w-100", data: { controller: "tweet-form" } do |f| %>
      <%= f.text_area :body, placeholder: tweet_placeholder, class: "form-control tweet-input w-100" %>
      <div class="d-flex justify-content-end">
        <%= f.submit button_label, class: "btn btn-lg btn-twitter rounded-pill" %>
      </div>
    <% end %>
  </div>
</div>